version: "3.4"
services:
  tpdp_site:
    build: site
    restart: always
    network_mode: host
    env_file: .env
  tpdp_core:
    build: core
    restart: always
    network_mode: host
    env_file: .env
    depends_on:
      - tpdp_postgres
  tpdp_postgres:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: host
    env_file: .env

volumes:
  postgres_data:
