version: "3.4"
services:
  tpdp_site:
    build: site
    restart: always
    network_mode: host
    env_file: .env
  tpdp_core:
    build: core
    restart: always
    network_mode: host
    env_file: .env
  tpdp_postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    env_file: .env
